In [9]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Tambah data ke-21
X1 = np.random.normal(loc=1, scale=10, size=(1000, 1))
print("Nilai X1 : ",X1)

# Generate a synthetic classification dataset
X2, y = make_classification(n_samples=1000, n_features=21, n_informative=10, n_redundant=5, n_classes=2, random_state=42)

#Gabungkan data
X = np.hstack((X1, X2))

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Nilai X1 :  [[ 1.11714420e+01]
 [-5.53854427e+00]
 [ 7.16463082e+00]
 [-8.07763330e-01]
 [-1.40438925e+00]
 [ 2.15587024e+01]
 [ 1.44931142e+01]
 [-1.39098684e+00]
 [ 1.00943501e+01]
 [ 1.30017764e+01]
 [-1.56718983e+01]
 [ 8.41902593e+00]
 [-8.52768401e+00]
 [-2.05320727e+00]
 [-5.25004954e-01]
 [ 2.98429131e-01]
 [ 8.50724794e-01]
 [ 4.74830115e+00]
 [ 2.26733342e+01]
 [-1.20291993e+01]
 [-2.72957457e+00]
 [ 5.51099586e+00]
 [ 1.29612893e+01]
 [ 2.51578467e+00]
 [-4.42372058e-01]
 [ 1.59434718e+01]
 [-1.40428507e+01]
 [ 1.49579344e+01]
 [ 3.69298217e+00]
 [ 4.14841815e-01]
 [ 1.53382103e+01]
 [ 1.10985613e+01]
 [-6.95502898e+00]
 [ 8.66557658e+00]
 [ 2.65948354e+00]
 [-3.90089061e+00]
 [ 6.88123996e+00]
 [ 4.84010725e+00]
 [ 4.64684545e+00]
 [-3.94070210e+00]
 [-5.27869760e+00]
 [ 1.25147375e+01]
 [ 7.69955641e+00]
 [-1.32657376e+01]
 [ 2.03968437e+01]
 [ 2.30589926e+00]
 [-1.02374006e+01]
 [ 2.57402303e+00]
 [ 6.98639961e+00]
 [ 9.50537646e-01]
 [ 5.62494424e-01]
 [ 9.39638220e+00]


In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Initialize the Sequential model with an Input layer
model = Sequential([
    Input(shape=(X_train.shape[1],)) # Explicitly define input shape
])

# Add the first hidden layer
model.add(Dense(units=64, activation='relu'))

# Add a second hidden layer
model.add(Dense(units=32, activation='relu'))

# Add the output layer (1 unit with sigmoid activation for binary classification)
model.add(Dense(units=1, activation='sigmoid'))

# Print the model summary to display the architecture
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                │ (None, 64)             │         1,472 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,585 (14.00 KB)

 Trainable params: 3,585 (14.00 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Fungsi untuk membuat model baru (reset setiap run)
def create_model():
    model = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model
# Kombinasi parameter
configs = [
    (5, 16),
    (10, 16),
    (5, 32),
    (10, 32)
]
histories = {}
models = {}
for epochs, batch_size in configs:
    print(f"\nTraining dengan epochs={epochs}, batch_size={batch_size}")

    model = create_model()  # reset model

    history = model.fit(
        X_train, y_train,
        epochs=epochs,
        batch_size=batch_size,
        validation_split=0.2,
        verbose=1
    )
    key = f"epochs_{epochs}_batch_{batch_size}"
    histories[key] = history
    models[key] = model # Menyimpan objek model yang telah dilatih
print("\nSemua kombinasi training selesai. History tersimpan di 'histories'.")
print("Objek model yang telah dilatih tersimpan di 'models'.")


Training dengan epochs=5, batch_size=16
Epoch 1/5


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.5720 - loss: 0.8644 - val_accuracy: 0.6429 - val_loss: 0.6303
Epoch 2/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8090 - loss: 0.4848 - val_accuracy: 0.7214 - val_loss: 0.5332
Epoch 3/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8425 - loss: 0.3817 - val_accuracy: 0.7857 - val_loss: 0.4689
Epoch 4/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8950 - loss: 0.3081 - val_accuracy: 0.8143 - val_loss: 0.4218
Epoch 5/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9327 - loss: 0.2361 - val_accuracy: 0.8429 - val_loss: 0.3959

Training dengan epochs=10, batch_size=16
Epoch 1/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5960 - loss: 0.8114 - val_accuracy: 0.7571 - val_loss: 0.5375
Epoch 2/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8198 - loss: 0.4475 - val_accuracy: 0.8571 - val_loss: 0.4319
Epoch 3/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8502 - loss: 0.3670 - va

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

for key, model in models.items():
    print(f"\n=== Evaluasi untuk {key} ===")

    # Prediksi
    y_pred_proba = model.predict(X_test)
    y_pred_classes = (y_pred_proba > 0.5).astype(int)

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred_classes)
    print("Confusion Matrix:")
    print(cm)

    # Metrics
    acc = accuracy_score(y_test, y_pred_classes)
    prec = precision_score(y_test, y_pred_classes)
    rec = recall_score(y_test, y_pred_classes)
    f1 = f1_score(y_test, y_pred_classes)

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")


=== Evaluasi untuk epochs_5_batch_16 ===
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
Confusion Matrix:
[[139  19]
 [ 21 121]]
Accuracy  : 0.8667
Precision : 0.8643
Recall    : 0.8521
F1-Score  : 0.8582

=== Evaluasi untuk epochs_10_batch_16 ===
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 
Confusion Matrix:
[[142  16]
 [ 12 130]]
Accuracy  : 0.9067
Precision : 0.8904
Recall    : 0.9155
F1-Score  : 0.9028

=== Evaluasi untuk epochs_5_batch_32 ===
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 
Confusion Matrix:
[[136  22]
 [ 13 129]]
Accuracy  : 0.8833
Precision : 0.8543
Recall    : 0.9085
F1-Score  : 0.8805

=== Evaluasi untuk epochs_10_batch_32 ===
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 
Confusion Matrix:
[[141  17]
 [ 13 129]]
Accuracy  : 0.9000
Precision : 0.8836
Recall    : 0.9085
F1-Score  : 0.8958
